spring.application.name=testes


# ========================
# Configuração do DataSource - Neon PostgreSQL
# ========================

spring.datasource.url=jdbc:postgresql://ep-morning-resonance-an2x4ehu.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_DLbQSy42lema
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# Configuração do JPA / Hibernate
# ========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true